services:
    - docker

env:
    global:
        - COMMIT=${TRAVIS_COMMIT::8}
        - REPO=trafex/alpine-nginx-php7

script:
  - docker --version
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker push $REPO
