version: '2'

services:

    php-fpm:
      build:
        context: ./php
      volumes:
        - /home/docker_user/peter/www/html:/var/www/html
      expose:
        - "9000"
      depends_on:
        - mysql

    nginx:
      build:
        context: ./nginx
      volumes:
          - /home/docker_user/peter/www/html:/var/www/html
      ports:
          - "10181:80"
          - "10281:443"
          - "10122:22"
      depends_on:
          - php-fpm

    mysql:
      image: mysql:5.7
      volumes:
        - /home/docker/mysql:/var/lib/mysql
      ports:
        - "13306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=123456
